backend:
  name: git-gateway
  branch: main
  repo: syrkis/ptmkin.org
  site_domain: ptmkin.org

media_folder: static/images
public_folder: /images

collections:

  - name: "exhibition"
    label: "Exhibition"
    folder: "src/lib/content/exhibition"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "artist", label: "Artist", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "start", label: "Date", widget: "datetime" }
      - { name: "end", label: "End Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "image", label: "Image", widget: "image" }
  - name: "articles"
    label: "Article"
    folder: "src/lib/content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "image", label: "Image", widget: "image" }