backend:
  name: git-gateway
  branch: main
  repo: syrkis/ptmkin.org
  site_domain: ptmkin.org

media_folder: static/images
public_folder: /images

collections:
  - name: "posts"
    label: "Exhibitions"
    folder: "static/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }